### ISSUE TITLE
Panic when mounting pool

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/zos#1009]
Node: A34YUGenHKyhjDMAUKZe4cVDtJM2wQ4n4XRkfGUUEYdy

```

  | 2020-10-26 11:25:47 | [+] storaged: 2020-10-26T10:25:47Z debug checking device: /dev/sdc
-- | -- | --
  |   | 2020-10-26 11:25:47 | [+] storaged: 2020-10-26T10:25:47Z debug shutting down device /dev/sdb because it is not mounted and the device is on
  |   | 2020-10-26 11:25:47 | [+] storaged: 2020-10-26T10:25:47Z debug checking device: /dev/sdb
  |   | 2020-10-26 11:25:47 | [+] storaged: 2020-10-26T10:25:47Z debug checking device: /dev/sdk
  |   | 2020-10-26 11:25:47 | [+] storaged: 2020-10-26T10:25:47Z debug checking device: /dev/sdi


2020-10-26 11:25:46 | [-] storaged: panic: runtime error: index out of range [0] with length 0
-- | --
  |   | 2020-10-26 11:25:46 | [-] storaged: 	/home/runner/work/zos/zos/cmds/storaged/main.go:43 +0x40b
  |   | 2020-10-26 11:25:46 | [-] storaged: main.main()
  |   | 2020-10-26 11:25:46 | [-] storaged: 	/home/runner/work/zos/zos/pkg/storage/storage.go:69 +0x1ac
  |   | 2020-10-26 11:25:46 | [-] storaged: github.com/threefoldtech/zos/pkg/storage.New(0x0, 0x0, 0x0, 0x0)
  |   | 2020-10-26 11:25:46 | [-] storaged: 	/home/runner/work/zos/zos/pkg/storage/storage.go:182 +0x33e
  |   | 2020-10-26 11:25:46 | [-] storaged: github.com/threefoldtech/zos/pkg/storage.(*storageModule).initialize(0xc0004435e0, 0xe5b411, 0x6, 0xc000430001, 0x0, 0x0)
  |   | 2020-10-26 11:25:46 | [-] storaged: 	/home/runner/work/zos/zos/pkg/storage/filesystem/btrfs.go:229 +0x525
  |   | 2020-10-26 11:25:46 | [-] storaged: github.com/threefoldtech/zos/pkg/storage/filesystem.(*btrfsPool).Mount(0xc000344600, 0x1009560, 0xc0004404e0, 0xea19b0, 0xc0002a9000)
  |   | 2020-10-26 11:25:46 | [-] storaged: goroutine 1 [running]:
  |   | 2020-10-26 11:25:46 | [-] storaged:


2020-10-26 11:25:46 | [-] storaged:
-- | --
  |   | 2020-10-26 11:25:46 | [+] storaged: 2020-10-26T10:25:46Z debug pool usage device=/dev/sda size=11999601754112
  |   | 2020-10-26 11:25:46 | [+] storaged: 2020-10-26T10:25:46Z debug seektime disk=/dev/sdam type=HDD
  |   | 2020-10-26 11:25:46 | [+] storaged: 2020-10-26T10:25:46Z info Checking pools for disks that should be shutdown...
  |   | 2020-10-26 11:25:46 | [+] storaged: 2020-10-26T10:25:46Z debug pool usage device=/dev/sdc size=3000034656256
  |   | 2020-10-26 11:25:46 | [+] storaged: 2020-10-26T10:25:46Z debug pool usage device=/dev/sdb size=3000034656256
  |   | 2020-10-26 11:25:46 | [+] storaged: 2020-10-26T10:25:46Z debug pool usage device=/dev/sda size=11999601754112
  |   | 2020-10-26 11:25:46 | [+] storaged: 2020-10-26T10:25:46Z debug checking device: /dev/sdg
  |   | 2020-10-26 11:25:46 | [+] storaged: 2020-10-26T10:25:46Z debug checking device: /dev/sdf
  |   | 2020-10-26 11:25:46 | [+] storaged: 2020-10-26T10:25:46Z debug checking device: /dev/sdc


```

**Comment by DylanVerstraete** [comment]
Investigation led me to understand that this node has multiple issues:

- It's running on `0.2.2-rc5` which is an outdated version of zos
- It is booted with a non existing farmer id eg. `1` http://explorer.testnet.grid.tf/explorer/farms/1
- Someone tampered with the disks or btrfs did some weird stuff:
![Screenshot from 2020-10-26 13-54-41](https://user-images.githubusercontent.com/17138347/97184467-3ae11300-179f-11eb-88c8-98e785cdcdc3.png)
