### ISSUE TITLE
provisioning of k8s vm seems to be stuck

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#1032]
Seen on nodes:
```
A7FmQZ72h7FzjkJMGXmzLDFyfyxzitDZYuernGG97nv7
2fi9ZZiBGW4G9pnrN656bMfW6x55RSoHDeMrd9pgSA8T
BDhpLyV28Y6Njy54WnB2Rkn6eHdEUbMu3GwTTs65rGAG
93qJrfeBqYiuVC973n9kPX79uA4rZU6oHL9pdJGBegHL
DNav25NSCpx8NHwX11CUoUMsr2VW42sGoFCx6dtxyMV9
2imakaznKfYx3vA4CDcTKxWbw9GcW3eXX8wQfr61X1Lz
DyuhYMRR5c6PCPYTaFGpoN5iheo87ubKRvsLzinBzHHJ
FDQJLM3NJCMzSdvb1qbigzotBg2WgSyLCJQFRAAyAP5e
2tzdPqM5xrFHkn264GHyUzXQda9UxFGcWMR9BeN54FTi
GLyFeBes9meAxfW44HhRHJGL9yR1i4oxUHrkqvA7UTSP
72CP8QPhMSpF7MbSvNR1TYZFbTnbRiuyvq5xwcoRNAib
8BFWcddW79cawvjnuUMw8M5s9FqS3pHhMHvzn3pgCUiB
3dAnxcykEDgKVQdTRKmktggL2MZbm3CPSdS9Tdoy4HAF
6m9gFPTYLRiCH7FD8yU5VWwXZdfegKUvXZgrJoS1EJfQ
2m3nHPSAMyZFSeg5HPozic2NGBMtrXrBkhtNcVmd5Ss6
```

Logs from 93qJrfeBqYiuVC973n9kPX79uA4rZU6oHL9pdJGBegHL
```
[+] provisiond: 2020-10-29T07:38:13Z info provision statistics container=0 cru=0 delegateDomain=0 hru=0 k8sVM=0 mru=0 network=1 proxy=0 reverseProxy=0 sru=100 subdomain=0 volume=0 zDBNamespace=0
[+] provisiond: 2020-10-29T07:38:13Z info start provisioning reservation duration=2562047h47m16.854775807s expired=false id=494298-1 tag= to-delete=false type=kubernetes
[+] networkd: 2020-10-29T07:38:13Z info Checking if tap interface exists network-id=GV4UDCFm7ZGB6
[+] flistd: 2020-10-29T07:38:13Z info request to mount flist storage= url=https://hub.grid.tf/tf-official-apps/k3os.flist
[+] flistd: 2020-10-29T07:38:13Z info flist already in on the filesystem url=https://hub.grid.tf/tf-official-apps/k3os.flist
[+] flistd: 2020-10-29T07:38:13Z info starting 0-fs daemon args=["-ro","-cache","/var/cache/modules/flistd/cache","-meta","/var/cache/modules/flistd/flist/c3294b6ae242d1a5e6849c9f92cc75e7","-storage-url","zdb://hub.grid.tf:9900","-daemon","-pid","/var/cache/modules/flistd/pid/494298-1.pid","-log","/var/cache/modules/flistd/log/494298-1.log","/var/cache/modules/flistd/mountpoint/494298-1"] storage= url=https://hub.grid.tf/tf-official-apps/k3os.flist
```
After this, provisiond does't not finishes the provisioning and do not process any new reservation

**Comment by muhamadazmy** [comment]
I found this panic in the node logs, I am not sure if it's related to this or not 
```
[+] provisiond: 2020-10-29T07:46:16Z error failed to get next job. Retrying in 1 second error=EOF
[-] provisiond: panic: EOF
[-] provisiond: 
[-] provisiond: goroutine 1 [running]:
[-] provisiond: github.com/threefoldtech/zos/pkg/stubs.(*VDiskModuleStub).Exists(0xc0002cd070, 0xc0003d6c70, 0xc, 0x2)
[-] provisiond: 	/home/runner/work/zos/zos/pkg/stubs/vdisk_stub.go:58 +0x1d7
[-] provisiond: github.com/threefoldtech/zos/pkg/provision/primitives.(*Provisioner).kubernetesProvisionImpl(0xc0001a73e0, 0x108e0e0, 0xc00033a140, 0xc000154780, 0xc0002ec640, 0x8, 0xc00033fda0, 0xb, 0x0, 0x0)
[-] provisiond: 	/home/runner/work/zos/zos/pkg/provision/primitives/kubernetes.go:118 +0x7e5
[-] provisiond: github.com/threefoldtech/zos/pkg/provision/primitives.(*Provisioner).kubernetesProvision(...)
[-] provisiond: 	/home/runner/work/zos/zos/pkg/provision/primitives/kubernetes.go:53
[-] provisiond: github.com/threefoldtech/zos/pkg/provision.(*Engine).provision(0xc0003a4080, 0x108e0e0, 0xc00033a140, 0xc000154780, 0x0, 0xc000670000)
[-] provisiond: 	/home/runner/work/zos/zos/pkg/provision/engine.go:209 +0x174
[-] provisiond: github.com/threefoldtech/zos/pkg/provision.(*Engine).Run(0xc0003a4080, 0x108e0e0, 0xc00033a140, 0x0, 0x0)
[-] provisiond: 	/home/runner/work/zos/zos/pkg/provision/engine.go:142 +0xbd1
[-] provisiond: main.main()
[-] provisiond: 	/home/runner/work/zos/zos/cmds/provisiond/main.go:164 +0xff0
[+] provisiond: 2020-10-29T07:46:18Z info restart detected, keep reservation cache intact
[+] provisiond: 2020-10-29T07:46:18Z info updating reservation results
[+] provisiond: 2020-10-29T07:46:18Z info starting provision module broker=unix:///var/run/redis.sock
```

**Comment by muhamadazmy** [comment]
logs from storaged
```
[+] storaged: 2020-10-29T07:45:15Z debug checking device: /dev/sdd
[+] storaged: 2020-10-29T07:45:15Z debug checking device: /dev/sdc
[+] storaged: 2020-10-29T07:46:16Z error failed to get next job. Retrying in 1 second error=EOF
[+] storaged: 2020-10-29T07:46:17Z error failed to get next job. Retrying in 1 second error="dial unix /var/run/redis.sock: connect: no such file or directory"
[+] storaged: 2020-10-29T07:50:15Z info Checking pools for disks that should be shutdown...
[+] storaged: 2020-10-29T07:50:15Z debug checking device: /dev/sda
[+] storaged: 2020-10-29T07:50:15Z debug checking device: /dev/sdb
```

**Comment by muhamadazmy** [comment]
The panic in the zbus stubs is only raised if the failures is on the protocol level. My idea to make sure that failure in serialization and/or objects versions are noticable immediately, may be it's better now to return a proper error type instead.

This will only fix the panic, it won't explain why redis was not behaving.

**Comment by zaibon** [comment]
The panic you see is not related. It's was just me investigating I restart redis to make sure that was not something stuck in there.
You can ignore those.

**Comment by zaibon** [comment]
After investigation I found out that on these nodes storaged did not start the vdisk module because of a bug that is already solved there: https://github.com/threefoldtech/zos/commit/b28c5b3639c4b9ddbed2bd5d8c4364458e77d41b

when patching storaged with the fix, provisiond just keep provisioning the K8S VM just fine.

So I'll just close this cause it will be solved once we release the new RC on testnet containing the fix.
