### ISSUE TITLE
Network Deployment fails with no explorer errors

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/zos#1072]
Deploying a network on node `2imakaznKfYx3vA4CDcTKxWbw9GcW3eXX8wQfr61X1Lz ` fails with no explorer side errors 
 workload ID: 508598
```
Traceback (most recent call last):

  File "/root/js-ng/js-sdk/jumpscale/sals/reservation_chatflow/deployer.py", line 302, in dry_run
    deployer.wait_workload(wid, bot, 2)
    │        │             │    └ None
    │        │             └ 508598
    │        └ <function ChatflowDeployer.wait_workload at 0x7f26a26bfae8>
    └ <jumpscale.sals.reservation_chatflow.deployer.ChatflowDeployer object at 0x7f26a26ca470>

  File "/root/js-ng/js-sdk/jumpscale/sals/reservation_chatflow/deployer.py", line 897, in wait_workload
    raise DeploymentFailed(f"Workload {workload_id} failed to deploy in time")
          └ <class 'jumpscale.sals.reservation_chatflow.deployer.DeploymentFailed'>

jumpscale.sals.reservation_chatflow.deployer.DeploymentFailed: (DeploymentFailed(...), 'Workload 508598 failed to deploy in time')


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/root/js-ng/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 192, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f26a2e4dd08>
    └ <marketplacevdc.chats.cryptpad.CryptpadDeploy object at 0x7f26a1847668>

  File "/root/js-ng/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 200, in _execute_current_step
    wrapper(step_name)
    │       └ 'select_vdc'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f26a2619c80>

  File "/root/js-ng/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 192, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f26a2e4dd08>
    └ <marketplacevdc.chats.cryptpad.CryptpadDeploy object at 0x7f26a1847668>

  File "/root/js-ng/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 200, in _execute_current_step
    wrapper(step_name)
    │       └ 'create_subdomain'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f26a8d200d0>

> File "/root/js-ng/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 147, in wrapper
    getattr(self, step_name)()
            │     └ 'create_subdomain'
            └ <marketplacevdc.chats.cryptpad.CryptpadDeploy object at 0x7f26a1847668>

  File "/root/js-ng/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 658, in wrapper
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<marketplacevdc.chats.cryptpad.CryptpadDeploy object at 0x7f26a1847668>,)
           └ <function SolutionsChatflowDeploy.create_subdomain at 0x7f26a25ebe18>

  File "/root/js-ng/js-sdk/jumpscale/packages/marketplacevdc/sals/solutions_chatflow.py", line 266, in create_subdomain
    self._deploy()
    │    └ <function SolutionsChatflowDeploy._deploy at 0x7f26a25ebae8>
    └ <marketplacevdc.chats.cryptpad.CryptpadDeploy object at 0x7f26a1847668>

  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
           │     │       └ {}
           │     └ (<marketplacevdc.chats.cryptpad.CryptpadDeploy object at 0x7f26a1847668>,)
           └ <function SolutionsChatflowDeploy._deploy at 0x7f26a25eba60>

  File "/root/js-ng/js-sdk/jumpscale/packages/marketplacevdc/sals/solutions_chatflow.py", line 233, in _deploy
    **metadata,
      └ {'name': 'test22', 'form_info': {'chatflow': 'cryptpad', 'Solution name': 'test22'}}

  File "/root/js-ng/js-sdk/jumpscale/sals/reservation_chatflow/deployer.py", line 1582, in expose_and_create_certificate
    res = self.add_network_node(network_name, node, pool_id, identity_name=identity_name, bot=bot)
          │    │                │             │     │        │             │              │   └ None
          │    │                │             │     │        │             │              └ None
          │    │                │             │     │        │             └ None
          │    │                │             │     │        └ None
          │    │                │             │     └ 5437
          │    │                │             └ Node(
          │    │                │                 node_id='2imakaznKfYx3vA4CDcTKxWbw9GcW3eXX8wQfr61X1Lz',
          │    │                │                 node_id_v1='002590f2d66e',
          │    │                │                 farm_id=71,
          │    │                │                 os_version='0.4....
          │    │                └ 'k8stest'
          │    └ <function ChatflowDeployer.add_network_node at 0x7f26a26bfb70>
          └ <jumpscale.sals.marketplace.deployer.MarketPlaceDeployer object at 0x7f26a2694d68>

  File "/root/js-ng/js-sdk/jumpscale/sals/reservation_chatflow/deployer.py", line 933, in add_network_node
    breaking_node_ids=[node.node_id],
                       │    └ <property object at 0x7f26a8d89ae8>
                       └ Node(
                           node_id='2imakaznKfYx3vA4CDcTKxWbw9GcW3eXX8wQfr61X1Lz',
                           node_id_v1='002590f2d66e',
                           farm_id=71,
                           os_version='0.4....

  File "/root/js-ng/js-sdk/jumpscale/sals/reservation_chatflow/deployer.py", line 310, in dry_run
    "Network nodes dry run failed on node" f" {network.network_resources[idx].info.node_id}", wid=wid
                                                                                              │   └ 508598
                                                                                              └ 508598

jumpscale.sals.reservation_chatflow.deployer.DeploymentFailed: (DeploymentFailed(...), 'Network nodes dry run failed on node 2imakaznKfYx3vA4CDcTKxWbw9GcW3eXX8wQfr61X1Lz')

```

**Comment by muhamadazmy** [comment]
What is `Network nodes dry run` ?

**Comment by ranatrk** [comment]
it tries to deploy a network resource on a node to make sure the node is accepting reservations and working ok

**Comment by zaibon** [comment]
So it seems the dry run did his job perfectly here. The node didn't processed the reservation and you got an exception, right ?

**Comment by ranatrk** [comment]
yes, the first error occurred because timeout(its supposd to be 3 minutes) but in reality it took couple of seconds before this error

**Comment by muhamadazmy** [comment]
Issue is not relevant anymore. Please open a new one if this still an issue
