### ISSUE TITLE
vm doesn't restart after node reboot

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/zos#1472]
It seems that the tap interface dosn't get created in a timely fashion when a node reboots, hence vms can't start in time.
attached a `vmd` log

CH starts before redis ?

```
~ # zinit log vmd
[+] vmd: 2021-11-08T11:47:19Z info starting vmd module broker=unix:///var/run/redis.sock worker nr=1
[+] vmd: 2021-11-08T11:47:28Z debug saving machine name=97-505-ubuntu
[+] vmd: 2021-11-08T11:47:28Z debug checking device type name=t-9RajEsNKB1EH9 type=tuntap
[+] vmd: 2021-11-08T11:47:28Z debug ch: [setsid cloud-hypervisor --cpus boot=2 --memory size=4096M,shared=on --log-file /var/cache/modules/vmd/logs/97-505-ubuntu --api-socket /var/run/cloud-hypervisor/97-505-ubuntu --fs tag=/dev/root,socket=/var/run/virtio-97-505-ubuntu-0.socket --initramfs /var/cache/modules/flistd/mountpoint/cloud-container:dee1f2f9b4fe82cc9c06cad26c36bb93/initramfs-linux.img --disk path=/mnt/dc6e9e65-bfc4-4382-aa0c-dd2aa3e8a0ed/vdisks/97-505-testDiskBench,readonly=off --cmdline reboot=k root=/dev/root host=ubuntu rw net_eth0=10.1.4.2/24;fd57:6a77:6d4a:4::2/64 net_dns=8.8.8.8;1.1.1.1;2001:4860:4860::8888 panic=1 console=ttyS0 rootfstype=virtiofs vda=/data net_r4=default,10.1.4.1;10.1.0.0/16,10.1.4.1;100.64.0.0/16,10.1.4.1 net_r6=default,fd57:6a77:6d4a:4::1 init=/init.sh --console off --serial file=/var/cache/modules/vmd/logs/97-505-ubuntu.console --net tap=t-9RajEsNKB1EH9 --kernel /var/cache/modules/flistd/mountpoint/cloud-container:dee1f2f9b4fe82cc9c06cad26c36bb93/kernel]
[+] vmd: 2021-11-08T11:47:29Z debug trying to restart the vm id=97-506-mr name=97-506-mr
[+] vmd: 2021-11-08T11:47:29Z debug checking device type name=t-BLyPTXHfXyYB3 type=tuntap
[+] vmd: 2021-11-08T11:47:29Z debug ch: [setsid cloud-hypervisor --api-socket /var/run/cloud-hypervisor/97-506-mr --net tap=t-BLyPTXHfXyYB3 --kernel /var/cache/modules/flistd/mountpoint/cloud-container:dee1f2f9b4fe82cc9c06cad26c36bb93/kernel --cmdline panic=1 root=/dev/root rw vda=/mydisk net_r4=default,10.1.4.1;10.1.0.0/16,10.1.4.1;100.64.0.0/16,10.1.4.1 net_eth0=10.1.4.254/24;fd57:6a77:6d4a:4::fe/64 host=mr console=ttyS0 reboot=k rootfstype=virtiofs net_r6=default,fd57:6a77:6d4a:4::1 net_dns=8.8.8.8;1.1.1.1;2001:4860:4860::8888 init=/sbin/zinit "init" --log-file /var/cache/modules/vmd/logs/97-506-mr --serial file=/var/cache/modules/vmd/logs/97-506-mr.console --fs tag=/dev/root,socket=/var/run/virtio-97-506-mr-0.socket --initramfs /var/cache/modules/flistd/mountpoint/cloud-container:dee1f2f9b4fe82cc9c06cad26c36bb93/initramfs-linux.img --disk path=/mnt/dc6e9e65-bfc4-4382-aa0c-dd2aa3e8a0ed/vdisks/97-506-mrdisk,readonly=off --cpus boot=2 --memory size=2048M,shared=on --console off]
[+] vmd: 2021-11-08T11:47:29Z debug trying to restart the vm id=97-506-w0 name=97-506-w0
[+] vmd: 2021-11-08T11:47:29Z debug deleting vm due to restart error error="failed to detect interface type 't-AyD8PpDowjFmW': Link not found" id=97-506-w0
[+] vmd: 2021-11-08T11:47:29Z error failed to get next job. Retrying in 1 second error=EOF
[+] vmd: panic: dial unix /var/run/redis.sock: connect: connection refused
[+] vmd: 
[+] vmd: goroutine 98 [running]:
[+] vmd: github.com/threefoldtech/zos/pkg/stubs.(*ProvisionStub).DecommissionCached(0xc000735c28, {0x16d9398, 0xc000404980}, {0xc0002be67e, 0x9}, {0xc0001ce3c0, 0x41})
[+] vmd: 	/home/runner/work/zos/zos/pkg/stubs/provision_stub.go:54 +0x214
[+] vmd: github.com/threefoldtech/zos/pkg/vm.(*Module).monitorID(0xc000404940, {0x16d9398, 0xc000404980}, 0xc0000a8100, {0xc0002be67e, 0x9})
[+] vmd: 	/home/runner/work/zos/zos/pkg/vm/monitor.go:141 +0x81d
[+] vmd: github.com/threefoldtech/zos/pkg/vm.(*Module).monitor(0xc000404940, {0x16d9398, 0xc000404980})
[+] vmd: 	/home/runner/work/zos/zos/pkg/vm/monitor.go:72 +0x31f
[+] vmd: github.com/threefoldtech/zos/pkg/vm.(*Module).Monitor.func1()
[+] vmd: 	/home/runner/work/zos/zos/pkg/vm/monitor.go:35 +0xc6
[+] vmd: created by github.com/threefoldtech/zos/pkg/vm.(*Module).Monitor
[+] vmd: 	/home/runner/work/zos/zos/pkg/vm/monitor.go:31 +0x9a
[+] vmd: 2021-11-08T11:48:25Z info starting vmd module broker=unix:///var/run/redis.sock worker nr=1
[+] vmd: 2021-11-08T11:48:35Z debug trying to restart the vm id=97-505-ubuntu name=97-505-ubuntu
[+] vmd: 2021-11-08T11:48:35Z debug checking device type name=t-9RajEsNKB1EH9 type=tuntap
[+] vmd: 2021-11-08T11:48:35Z debug ch: [setsid cloud-hypervisor --fs tag=/dev/root,socket=/var/run/virtio-97-505-ubuntu-0.socket --initramfs /var/cache/modules/flistd/mountpoint/cloud-container:dee1f2f9b4fe82cc9c06cad26c36bb93/initramfs-linux.img --disk path=/mnt/dc6e9e65-bfc4-4382-aa0c-dd2aa3e8a0ed/vdisks/97-505-testDiskBench,readonly=off --net tap=t-9RajEsNKB1EH9 --cmdline reboot=k root=/dev/root host=ubuntu rw net_eth0=10.1.4.2/24;fd57:6a77:6d4a:4::2/64 net_dns=8.8.8.8;1.1.1.1;2001:4860:4860::8888 panic=1 console=ttyS0 rootfstype=virtiofs vda=/data net_r4=default,10.1.4.1;10.1.0.0/16,10.1.4.1;100.64.0.0/16,10.1.4.1 net_r6=default,fd57:6a77:6d4a:4::1 init=/init.sh --log-file /var/cache/modules/vmd/logs/97-505-ubuntu --api-socket /var/run/cloud-hypervisor/97-505-ubuntu --console off --serial file=/var/cache/modules/vmd/logs/97-505-ubuntu.console --kernel /var/cache/modules/flistd/mountpoint/cloud-container:dee1f2f9b4fe82cc9c06cad26c36bb93/kernel --cpus boot=2 --memory size=4096M,shared=on]
[+] vmd: 2021-11-08T11:48:39Z debug deleting vm due to restart error error="failed to spawn vm machine process '97-505-ubuntu'" id=97-505-ubuntu
[+] vmd: 2021-11-08T11:48:53Z debug trying to restart the vm id=97-506-mr name=97-506-mr
[+] vmd: 2021-11-08T11:48:53Z debug checking device type name=t-BLyPTXHfXyYB3 type=tuntap
[+] vmd: 2021-11-08T11:48:53Z debug ch: [setsid cloud-hypervisor --cpus boot=2 --memory size=2048M,shared=on --console off --api-socket /var/run/cloud-hypervisor/97-506-mr --initramfs /var/cache/modules/flistd/mountpoint/cloud-container:dee1f2f9b4fe82cc9c06cad26c36bb93/initramfs-linux.img --disk path=/mnt/dc6e9e65-bfc4-4382-aa0c-dd2aa3e8a0ed/vdisks/97-506-mrdisk,readonly=off --kernel /var/cache/modules/flistd/mountpoint/cloud-container:dee1f2f9b4fe82cc9c06cad26c36bb93/kernel --cmdline panic=1 root=/dev/root rw vda=/mydisk net_r4=default,10.1.4.1;10.1.0.0/16,10.1.4.1;100.64.0.0/16,10.1.4.1 net_eth0=10.1.4.254/24;fd57:6a77:6d4a:4::fe/64 host=mr console=ttyS0 reboot=k rootfstype=virtiofs net_r6=default,fd57:6a77:6d4a:4::1 net_dns=8.8.8.8;1.1.1.1;2001:4860:4860::8888 init=/sbin/zinit "init" --net tap=t-BLyPTXHfXyYB3 --fs tag=/dev/root,socket=/var/run/virtio-97-506-mr-0.socket --log-file /var/cache/modules/vmd/logs/97-506-mr --serial file=/var/cache/modules/vmd/logs/97-506-mr.console]
[+] vmd: 2021-11-08T11:48:58Z debug deleting vm due to restart error error="failed to spawn vm machine process '97-506-mr'" id=97-506-mr
```

**Comment by muhamadazmy** [comment]
Yes, i found the issue and is part of this #1474
