### ISSUE TITLE
VM with QSFS deployment issue

### ISSUE THREAD

**Issue by georgeconstantinou** [threefoldtech/zos#1663]
When trying to deploy a VM with QSFS I receive the following error:

```bash
disconnecting
/home/george/Development/threefold/grid3_client_ts/src/high_level/twinDeploymentHandler.ts:387
throw Error(e);
^
Error: Error: Failed to deploy zdb with name wed2710q12 on node 17 due to: failed to create zdb namespace: failed to connect to 0-db: e862d149-d037-4357-ada3-efbfc4e2b3f6: dial unix /var/run/zdb_e862d149-d037-4357-ada3-efbfc4e2b3f6/zdb.sock: connect: connection refused
at TwinDeploymentHandler.handle (/home/george/Development/threefold/grid3_client_ts/src/high_level/twinDeploymentHandler.ts:387:19)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async QSFSZdbsModule.deploy (/home/george/Development/threefold/grid3_client_ts/src/modules/qsfs_zdbs.ts:57:27)
at async QSFSZdbsModule.descriptor.value (/home/george/Development/threefold/grid3_client_ts/src/modules/utils.ts:14:16)
at async QSFSZdbsModule.descriptor.value (/home/george/Development/threefold/grid3_client_ts/src/helpers/validator.ts:23:16)
at async main (/home/george/Development/threefold/grid3_client_ts/scripts/vm_with_qsfs.ts:75:17)
```

Moved from: https://circles.threefold.me/project/test-tfgrid3/issue/110

**Comment by muhamadazmy** [comment]
Closing because lack of debugging information. it's missing node, farm and contract information. There is noway to debug what happened on that zdb node that can cause this.

Please create a new issue with more details if it still relevant.

> Note: i understand that this happened during "deplying"the zdb. the deployer code need to try again and or move a complete different node if it failed to deploy one zdb instance!
