### ISSUE TITLE
panic in provisiond

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#592]
[-] provisiond: panic: runtime error: invalid memory address or nil pointer dereference
[-] provisiond: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x806467]
[-] provisiond: 
[-] provisiond: goroutine 21 [running]:
[-] provisiond: github.com/threefoldtech/zos/pkg/provision.ErrTemporary.Error(...)
[-] provisiond: 	/home/runner/work/zos/zos/pkg/provision/provision.go:71
[-] provisiond: github.com/rs/zerolog.(*Event).AnErr(0xc0002491a0, 0x8ea2ef, 0x5, 0x98f2e0, 0xc000542190, 0x10)
[-] provisiond: 	/home/runner/go/pkg/mod/github.com/rs/zerolog@v1.18.0/event.go:286 +0x108
[-] provisiond: github.com/rs/zerolog.(*Event).Err(0xc0002491a0, 0x98f2e0, 0xc000542190, 0xc0002491a0)
[-] provisiond: 	/home/runner/go/pkg/mod/github.com/rs/zerolog@v1.18.0/event.go:346 +0x76
[-] provisiond: github.com/threefoldtech/zos/pkg/provision.(*pollSource).Reservations.func1(0xc0003100c0, 0xc000263740, 0x9969a0, 0xc00030e000)
[-] provisiond: 	/home/runner/work/zos/zos/pkg/provision/source.go:69 +0x297
[-] provisiond: created by github.com/threefoldtech/zos/pkg/provision.(*pollSource).Reservations

**Comment by zaibon** [comment]
fixed by: https://github.com/threefoldtech/zos/commit/31d2e3eace8366f4e8e0e4915ba69db8dcd0a78b
