### ISSUE TITLE
networkd panic

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#877]
```
[+] networkd: 2020-07-30T10:42:27Z info set ip to container container=460390-1 ip=10.87.2.20 namespace=460390-1
[-] networkd: panic: runtime error: index out of range [-1]
[-] networkd: 
[-] networkd: goroutine 341 [running, locked to thread]:
[-] networkd: github.com/threefoldtech/zos/pkg/network/nr.(*NetResource).Join.func2(0x16ac320, 0xc000a27ba0, 0x0, 0x0)
[-] networkd: 	/home/runner/work/zos/zos/pkg/network/nr/container.go:100 +0x1544
[-] networkd: github.com/containernetworking/plugins/pkg/ns.(*netNS).Do.func1(0x16ac320, 0xc000a27ba0, 0x0, 0x0)
[-] networkd: 	/home/runner/go/pkg/mod/github.com/containernetworking/plugins@v0.8.4/pkg/ns/ns_linux.go:183 +0x288
[-] networkd: github.com/containernetworking/plugins/pkg/ns.(*netNS).Do.func2(0xc00038c460, 0xc000436bc0, 0x16ac320, 0xc000a27ba0, 0xc000a27bb0)
[-] networkd: 	/home/runner/go/pkg/mod/github.com/containernetworking/plugins@v0.8.4/pkg/ns/ns_linux.go:200 +0x6b
[-] networkd: created by github.com/containernetworking/plugins/pkg/ns.(*netNS).Do
[-] networkd: 	/home/runner/go/pkg/mod/github.com/containernetworking/plugins@v0.8.4/pkg/ns/ns_linux.go:197 +0x1f0
```

**Comment by zaibon** [comment]
fixed by https://github.com/threefoldtech/zos/commit/1342794609c6257af9484ad594825d8d53f59624
