### ISSUE TITLE
Provisiond hung

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/zos#918]
Provisiond was hung on following node: 3BwDVNRigau8Zk6BQkJt5PLxrHQnJ5NTfNvAtuubC1eS

On grafana we found no logs of the past 24h for provisiond. After a restart it was working again.

**Comment by zaibon** [comment]
Found a panic from provisiond, that could be related:
```
[+] provisiond: 2020-09-07T12:57:16Z info start provisioning reservation duration=2562047h47m16.854775807s expired=false id=476043-1 tag= to-delete=false type=container
[+] networkd: 2020-09-07T12:57:16Z info joining network network-id=DnfrytdUUU9iN
[+] networkd: 2020-09-07T12:57:16Z info Create veth pair in net namespace container=476043-1 namespace=476043-1 veth=eth0
[+] networkd: 2020-09-07T12:57:16Z info set ip to container container=476043-1 ip=10.53.5.2 namespace=476043-1
[+] networkd: 2020-09-07T12:57:16Z info set ip to container container=476043-1 ip=fd44:6e66:7279:5::2 namespace=476043-1
[-] networkd: panic: runtime error: index out of range [-1]
[-] networkd: 
[-] networkd: goroutine 8767 [running, locked to thread]:
[-] networkd: github.com/threefoldtech/zos/pkg/network/nr.(*NetResource).Join.func2(0x14c8220, 0xc0000932d0, 0x0, 0x0)
[-] networkd: 	/home/runner/work/zos/zos/pkg/network/nr/container.go:100 +0x150a
[-] networkd: github.com/containernetworking/plugins/pkg/ns.(*netNS).Do.func1(0x14c8220, 0xc0000932d0, 0x0, 0x0)
[-] networkd: 	/home/runner/go/pkg/mod/github.com/containernetworking/plugins@v0.8.4/pkg/ns/ns_linux.go:183 +0x293
[-] networkd: github.com/containernetworking/plugins/pkg/ns.(*netNS).Do.func2(0xc00031e810, 0xc0001fa740, 0x14c8220, 0xc0000932d0, 0xc0000932e0)
[-] networkd: 	/home/runner/go/pkg/mod/github.com/containernetworking/plugins@v0.8.4/pkg/ns/ns_linux.go:200 +0x6b
[-] networkd: created by github.com/containernetworking/plugins/pkg/ns.(*netNS).Do
[-] networkd: 	/home/runner/go/pkg/mod/github.com/containernetworking/plugins@v0.8.4/pkg/ns/ns_linux.go:197 +0x1f4
```

**Comment by muhamadazmy** [comment]
So provisiond is probably stuck on a call to networkd that will never return. I will look into this

**Comment by muhamadazmy** [comment]
That is the reservation that caused the problem http://explorer.testnet.grid.tf/api/v1/reservations/workloads/476043

- Checking the code this shouldn't happen unless the cached network resource object is corrupted. We will check the node in case we have any hardware issues.
